Repository vcgss/Hactoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#2 Create mergesort.c
  Sort Algos/mergesort.c
Labels: good first issue, hacktoberfest-accepted

#3 selection sort
  Sort Algos/selection_sort.c
Labels: hacktoberfest-accepted

#4 Create hash.c
  Hashing/hash.c
Labels: hacktoberfest-accepted

#5 Bubble sort
  bubblesort.c
Labels: hacktoberfest-accepted

#6 Update hash.c
  Hashing/hash.c
Labels: hacktoberfest-accepted

#12 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#14 Create linkedlist.c
  Linked List/linkedlist.c
Labels: hacktoberfest-accepted, Hactoberfest2022

#13 Create C Program to Delete duplicate elements from an array
  C Program to Delete duplicate elements from an array
Labels: good first issue, hacktoberfest-accepted

#16 Greedy Algorithms And Greedy Sorting Algorithms By ChandniJha630
  Sort Algos/bucket sort for fraction (0-1) by by ChandniJha630.cpp
  activity selection by ChandniJha630.cpp
  fractional knapsack by by ChandniJha630.cpp
Labels: hacktoberfest-accepted, Hactoberfest2022

#17 Implement stack and queue using singly linked list
  Linked List/stacknQueue.c
Labels: good first issue, hacktoberfest-accepted, Hactoberfest2022

#18 Create linearSearch.c
  Search/linearSearch.c
Labels: good first issue, hacktoberfest-accepted, Hactoberfest2022

#19 radix sort
  Sort Algos/radix_sort.c
Labels: hacktoberfest-accepted, Hactoberfest2022

#23 Create infixtopostfix.c
  infixtopostfix.c
Labels: hacktoberfest-accepted, Hactoberfest2022

#22 c program to merge two sorted array
  merge_two_sorted_array.c
Labels: hacktoberfest-accepted, Hactoberfest2022
